services:
  web:
    image: ghcr.io/exxxpm/devops-lab4-web:lab_4
    container_name: lab4-web
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      DATABASE_HOST: lab4-db
      DATABASE_NAME: lab4
      DATABASE_USER: lab4
      DATABASE_PASSWORD: lab4

  db:
    image: postgres:15
    container_name: lab4-db
    environment:
      POSTGRES_DB: lab4
      POSTGRES_USER: lab4
      POSTGRES_PASSWORD: lab4
    volumes:
      - lab4_data:/var/lib/postgresql/data

volumes:
  lab4_data:
