name: Lab 3 CD

on:
  push:
    branches: [ lab_3 ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2426 course.prafdin.ru >> ~/.ssh/known_hosts

      - name: Deploy container to VM
        run: |
          ssh -p 2426 deploy@course.prafdin.ru \
            "docker pull exxxpm/devops-lab3:latest && \
             docker stop lab3 || true && \
             docker rm lab3 || true && \
             docker run -d --name lab3 -p 8181:8181 exxxpm/devops-lab3:latest"
