name: Lab 3 CD

on:
  push:
    branches: [ "lab_3" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2426 course.prafdin.ru >> ~/.ssh/known_hosts

      - name: Deploy container to devops VM
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          ssh -p 2426 deploy@course.prafdin.ru <<'EOF'
          set -e

          IMAGE="ghcr.io/exxxpm/devops_labs:lab_3"

          echo "${GHCR_TOKEN}" | docker login ghcr.io -u exxxpm --password-stdin

          docker pull "$IMAGE"

          # Остановить старый контейнер, если есть
          docker stop devops-app || true
          docker rm devops-app || true

          # Запустить новый
          docker run -d --name devops-app --restart=always \
            -p 8181:8181 "$IMAGE"
          EOF
