name: Lab 3 CD

on:
  push:
    branches: [ "lab_3" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2426 course.prafdin.ru >> ~/.ssh/known_hosts

      - name: Deploy container on devops VM (lab_3)
        run: |
          ssh -p 2426 deploy@course.prafdin.ru \
            'BRANCH=lab_3 REPO_URL=https://github.com/exxxpm/DevOPS_labs.git /opt/app/deploy_lab3.sh'

